avanti/urls.py
from django.contrib.auth.views import LogoutView
from django.urls import path,reverse_lazy
from . import views

app_name = 'administrativo'

urlpatterns = [
    #Login
    path('accounts/login/', views.CustomLoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(next_page=reverse_lazy('default_main')), name='logout'),
    path('cambiar-password/', views.CustomPasswordChangeView.as_view(), name='cambiar_password'),
    #Main
    path('paciente/', views.ficha_clinica_paciente, name='paciente_main'),
    path('medico/', views.medico, name='medico_main'),
    path('administrativo/', views.personal, name='administrativo_main'),
    path('', views.home, name='default_main'),

    #Medicos desde vista administrativo
    path('registrar-medico/', views.registrar_medico, name='registrar_medico'),
    path('lista-medicos/', views.lista_medicos, name='lista_medicos'),
    path('editar_medico/<str:rut>/', views.editar_medico, name='editar_medico'),
    path('eliminar_medico/<str:rut>/', views.eliminar_medico, name='eliminar_medico'),

    #Disponibilidades
    path('crear-disponibilidad/<str:medico_rut>/', views.crear_disponibilidad, name='crear_disponibilidad'),
    path('ver-disponibilidades/<str:medico_rut>/', views.ver_disponibilidades, name='ver_disponibilidades'),
    path('editar-disponibilidad/<str:disponibilidad_id>/', views.editar_disponibilidad, name='editar_disponibilidad'),
    path('eliminar-disponibilidad/<str:disponibilidad_id>/', views.eliminar_disponibilidad, name='eliminar_disponibilidad'),
    #Horarios
    path('api/horarios/', views.HorarioFullCalendarView.as_view(), name='api_horarios'),
    path('api/horarios/<uuid:horario_id>/editar/', views.EditarHorarioView.as_view(), name='editar_horario'),
    path('api/horarios/<uuid:horario_id>/eliminar/', views.EliminarHorarioView.as_view(), name='eliminar_horario'), 
    path('generar_horarios/<str:rut_medico>/', views.generar_horario, name='generar_horarios'),
    path('ver-horarios/<str:medico_rut>/', views.ver_horarios, name='ver_horarios'),
    #Gestion Pacientes
    path('pacientes/', views.listar_pacientes, name='listar_pacientes'),
    path('pacientes/gestionar/', views.gestionar_paciente, name='gestionar_paciente'),
    path('pacientes/gestionar/<str:rut>/', views.gestionar_paciente, name='gestionar_paciente'),
    #Ficha Clinica
    path('crear_ficha/', views.crear_ficha_view, name='crear_ficha'),
    path('consultas/<str:rut>/', views.listado_consultas, name='listado_consultas'),
    path('<int:consulta_id>/detalle/', views.detalle_consulta, name='detalle_consulta_medico'),
    path('api/buscar_paciente/', views.buscar_paciente, name='buscar_paciente'),

    #Citas
    path('formulario-reserva/', views.formulario_reserva, name='formulario_reserva'),
    path('medicos/', views.citas_medicos, name='citas_medicos'),
    path('horarios/<str:medico_rut>/', views.ver_citas, name='ver_citas'),
    path('reservar_cita/', views.reservar_cita, name='reservar_cita'),
    path('resumen-cita/<str:cita_id>/', views.resumen_cita, name='resumen_cita'),
    path('error/', views.error_cita, name='error_cita'),

    #Citas ya generadas
    path('buscar/rut/', views.buscar_rut, name='buscar_rut'),  # Vista para ingresar el RUT
    path('citas/listado/<str:rut>', views.listado_citas, name='listado_citas'),  # Vista para mostrar las citas
    path('editar_cita/<str:medico_rut>/<str:cita>/', views.editar_cita, name='editar_cita'),
    path('cita/cancelar/<str:cita>/', views.cancelar_cita, name='cancelar_cita'),

    #Ficha desde Paciente
    path('consulta/<int:consulta_id>/', views.detalle_paciente_consulta, name='detalle_consulta'),
    #Horario Vista Medico
    path('horarios/', views.ver_horarios_medico, name='ver_horarios'),
    path('horarios/<uuid:horario_id>/detalles/', views.obtener_detalles_cita, name='detalles_cita'),
    path('horarios/<uuid:horario_id>/finalizar/', views.finalizar_cita, name='finalizar_cita'),
    #API para las salas
    path('api/salas/<str:sucursal_id>/', views.salas_por_sucursal, name='salas_por_sucursal'),
]

centromedico/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('avanti.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
]

avanti/models.py
from django.db import models

# Create your models here.

avanti/models/administrativo.py
from django.db import models

class Administrativo(models.Model):
    usuario = models.OneToOneField('Usuario', on_delete=models.CASCADE, primary_key=True, related_name='perfil_administrativo')
    cargo = models.CharField(max_length=50, blank=True, null=True)

    class Meta:
        db_table = 'administrativo'

    def __str__(self):
        return self.usuario.first_name

avanti/models/alergias.py
from django.db import models

class Alergia(models.Model):
    consulta = models.ForeignKey('Consulta', related_name='alergias', on_delete=models.CASCADE)
    descripcion = models.TextField()

    def __str__(self):
        return f"Alergia en consulta {self.consulta.fecha_consulta}"

avanti/models/bono.py
from django.db import models

class Bono(models.Model):
    bono = models.CharField(primary_key=True, max_length=20)
    monto = models.BigIntegerField(blank=True, null=True)
    feccreacion = models.DateField(blank=True, null=True)
    fecvigencia = models.DateField(blank=True, null=True)
    cita = models.ForeignKey('Cita', on_delete=models.CASCADE, db_column='id_cita')
    paciente = models.ForeignKey('Paciente', on_delete=models.CASCADE, related_name='bonos')
    prevision = models.ForeignKey('Prevision', on_delete=models.CASCADE, db_column='id_prevision', related_name='bonos')
    reporte = models.ForeignKey('Reportes', on_delete=models.CASCADE, db_column='id_reporte')
    administrativo = models.ForeignKey('Administrativo', on_delete=models.CASCADE)

    class Meta:
        db_table = 'bono'
        unique_together = (('bono', 'reporte', 'administrativo'),)

avanti/models/cita.py
from django.db import models

class Cita(models.Model):
    cita = models.CharField(primary_key=True, max_length=100)
    horario = models.ForeignKey('Horario', on_delete=models.CASCADE, db_column='id_horario', related_name='citas')
    prevision = models.ForeignKey('Prevision', on_delete=models.CASCADE, db_column='id_prevision')
    paciente = models.ForeignKey('Paciente', on_delete=models.CASCADE)
    finalizada = models.BooleanField(default=False)

    class Meta:
        db_table = 'cita'
        unique_together = (('cita', 'paciente', 'prevision'),)

avanti/models/consulta.py
from django.db import models

class Consulta(models.Model):
    fecha_consulta = models.DateField()
    motivo = models.TextField()
    observaciones = models.TextField()
    ficha_clinica = models.ForeignKey('FichaClinica', on_delete=models.CASCADE, related_name='consultas')
    medico = models.ForeignKey('Medico', on_delete=models.SET_NULL, null=True, blank=True, related_name='consultas')  # Relación con Medico


    def __str__(self):
        return f"Consulta {self.fecha_consulta} - {self.ficha_clinica.paciente.usuario.first_name}"

avanti/models/diagnosticos.py
from django.db import models

class Diagnostico(models.Model):
    consulta = models.ForeignKey('Consulta', related_name='diagnosticos', on_delete=models.CASCADE)
    descripcion = models.TextField()

    def __str__(self):
        return f"Diagnóstico en consulta {self.consulta.fecha_consulta}"

avanti/models/disponibilidad.py
from django.db import models
import uuid

class Disponibilidad(models.Model):
    DIAS_SEMANA = [
        ('L', 'Lunes'),
        ('M', 'Martes'),
        ('X', 'Miércoles'),
        ('J', 'Jueves'),
        ('V', 'Viernes'),
        ('S', 'Sábado'),
        ('D', 'Domingo'),
    ]
    disponibilidad = models.CharField(max_length=36, primary_key=True, default=uuid.uuid4, editable=False)
    medico = models.ForeignKey('Medico', on_delete=models.CASCADE)
    dia = models.CharField(max_length=1, choices=DIAS_SEMANA, default='L')  # Día de la semana
    horainicio = models.TimeField(blank=True, null=True)  # Hora de inicio
    horafin = models.TimeField(blank=True, null=True)    # Hora de fin

    class Meta:
        db_table = 'disponibilidad'
        unique_together = ('medico', 'dia', 'horainicio', 'horafin')


    def __str__(self):
        return f"{self.get_dia_display()} - {self.horainicio.strftime('%H:%M')} - {self.horafin.strftime('%H:%M')}"

avanti/models/enfermedadesbase.py
from django.db import models

class EnfermedadesBase(models.Model):
    consulta = models.ForeignKey('Consulta', related_name='enfermedades_base', on_delete=models.CASCADE)
    descripcion = models.TextField()

    def __str__(self):
        return f"Enfermedad Base en consulta {self.consulta.fecha_consulta}"

avanti/models/especialidad.py
from django.db import models

class Especialidad(models.Model):
    nombre = models.CharField(max_length=100, unique=True)

    class Meta:
        db_table = 'especialidad'
        verbose_name = 'Especialidad'
        verbose_name_plural = 'Especialidades'
        ordering = ['nombre']

    def __str__(self):
        return self.nombre

avanti/models/estado.py
from django.db import models

class Estado(models.Model):
    estado = models.CharField(primary_key=True, max_length=12)
    descripcion = models.CharField(max_length=30, blank=True, null=True)

    class Meta:
        db_table = 'estado'

avanti/models/fichaclinica.py
from django.db import models

class FichaClinica(models.Model):
    paciente = models.OneToOneField('Paciente', on_delete=models.CASCADE)
    edad = models.IntegerField()  # Edad directamente en la ficha clínica
    fecha_creacion = models.DateField(auto_now_add=True)

    def __str__(self):
        return f"Ficha Clínica de {self.paciente.usuario.first_name}"

avanti/models/historial.py
from django.db import models

class Historial(models.Model):
    ficha_clinica = models.ForeignKey('FichaClinica', on_delete=models.CASCADE, related_name='historiales')
    consulta = models.ForeignKey('Consulta', on_delete=models.CASCADE, related_name='historiales')
    fecha_registro = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"Historial del paciente {self.ficha_clinica.paciente.nombre} - Consulta {self.consulta.fecha_consulta}"

avanti/models/historialestado.py
from django.db import models

class HistorialEstado(models.Model):
    historialestado = models.CharField(primary_key=True, max_length=20)
    fechacambio = models.DateField(blank=True, null=True)
    estado = models.ForeignKey('Estado', models.CASCADE, db_column='id_estado')
    cita = models.ForeignKey('Cita', models.CASCADE, db_column='id_cita')
    prevision = models.ForeignKey('Prevision', models.CASCADE, db_column='prevision', to_field='prevision', related_name='historialestado_prevision_set'
    )
    paciente = models.ForeignKey('Paciente', models.CASCADE)

    class Meta:
        db_table = 'historial_estado'
        constraints = [
            models.UniqueConstraint(
                fields=['historialestado', 'estado', 'cita', 'prevision', 'paciente'],
                name='unique_historialestado'
            )
        ]

avanti/models/horario.py
from django.db import models
import uuid

class Horario(models.Model):
    horario = models.CharField(max_length=36, primary_key=True, default=uuid.uuid4, editable=False)
    medico = models.ForeignKey('Medico', on_delete=models.CASCADE)
    disponibilidad = models.ForeignKey('Disponibilidad',  on_delete=models.CASCADE, related_name='horarios')
    fechainicio = models.DateTimeField(blank=True, null=True)  # Fecha y hora de inicio del evento
    fechafin = models.DateTimeField(blank=True, null=True)    # Fecha y hora de fin del evento
    sala = models.ForeignKey('Sala', models.CASCADE, db_column='id_sala')
    
    disponible = models.BooleanField(default=True)
    
    class Meta:
        db_table = 'horario'
        unique_together = (('sala', 'medico', 'fechainicio', 'fechafin'))

avanti/models/medicamentos.py
from django.db import models

class Medicamento(models.Model):
    consulta = models.ForeignKey('Consulta', related_name='medicamentos', on_delete=models.CASCADE)
    nombre = models.CharField(max_length=100)

    def __str__(self):
        return f"Medicamento en consulta {self.consulta.fecha_consulta}"

avanti/models/medico.py
from django.db import models

class Medico(models.Model):
    usuario = models.OneToOneField('Usuario', on_delete=models.CASCADE, primary_key=True, related_name='perfil_medico')
    especialidad = models.ForeignKey('Especialidad', on_delete=models.PROTECT, related_name='medicos')

    class Meta:
        db_table = 'medico'

    def __str__(self):
        return self.usuario.first_name

avanti/models/metododepago.py
from django.db import models

class MetodoDePago(models.Model):
    metodo = models.CharField(primary_key=True, max_length=20)
    tipo = models.CharField(max_length=50, blank=True, null=True)

    class Meta:
        db_table = 'metodo_de_pago'

avanti/models/paciente.py
from django.db import models

class Paciente(models.Model):
    usuario = models.OneToOneField('Usuario', on_delete=models.CASCADE, primary_key=True, related_name='perfil_paciente')
    direccion = models.CharField(max_length=100, blank=True, null=True)

    class Meta:
        db_table = 'paciente'
    
    def __str__(self):
        return self.usuario.first_name

avanti/models/pago.py
from django.db import models


class Pago(models.Model):
    pago = models.CharField(max_length=20)
    monto = models.BigIntegerField(blank=True, null=True)
    fechapago = models.DateField(blank=True, null=True)
    bono = models.ForeignKey(
        'Bono', models.CASCADE, db_column='id_bono'
    )
    metodo = models.ForeignKey(
        'MetodoDePago', models.CASCADE, db_column='id_metodo'
    )
    reporte = models.ForeignKey(
        'Reportes', models.CASCADE, db_column='id_reporte', related_name='pago_id_reporte_set'
    )
    administrativo = models.ForeignKey('Administrativo', models.CASCADE)

    class Meta:
        db_table = 'pago'
        unique_together = (('pago', 'bono', 'reporte', 'administrativo', 'metodo'),)

avanti/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}Base{% endblock %}</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet">
    <link href="https://cdn.jsdelivr.net/npm/fullcalendar@6.1.8/main.min.css" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'css/estilo.css' %}">
    {% block extra_css %}
    {% endblock %}
</head>
<body>
    <header>
        <div class="container">
            <div class="d-flex justify-content-center flex-wrap text-center">
                <a href="tel:+56230001010" class="btn custom-btn-blue me-2 mb-2">📞 23 000 1010</a>
                <a href="mailto:info@centroavanti.cl" class="btn custom-btn-orange me-2 mb-2">✉️ info@centroavanti.cl</a>
                <a href="https://wa.me/56911111111" class="btn custom-btn-green mb-2">💬 +569 1111 1111</a>
            </div>
        </div>
    </header>

    <nav class="navbar navbar-expand-lg navbar-dark">
        <div class="container">
            <a class="navbar-brand d-flex align-items-center" href="{% url 'administrativo:default_main' %}">
                <img src="{% static 'imagenes/circular_logo.png' %}" alt="Logo" id="logo" href="{% url 'administrativo:default_main' %}">
                Centro Médico Avanti
            </a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNav">
                <ul class="navbar-nav ms-auto">
                    {% if user.is_authenticated %}
                    <li class="nav-item">
                        <a href="{% url 'administrativo:cambiar_password' %}" class="btn btn-outline-light me-2">Cambiar contraseña</a>
                    </li>
                    <li class="nav-item">
                        <form action="{% url 'logout' %}" method="post" class="d-inline">
                            {% csrf_token %}
                            <button type="submit" class="btn btn-outline-light">Cerrar sesión</button>
                        </form>
                    </li>
                    {% else %}
                    <li class="nav-item">
                        <a href="{% url 'login' %}" class="btn btn-outline-light">Iniciar sesión</a>
                    </li>
                    {% endif %}
                </ul>
            </div>
        </div>
    </nav>

    <div class="container mt-4">
        {% if messages %}
        <div class="alert alert-dismissible fade show">
            {% for message in messages %}
            <div class="alert alert-{{ message.tags }}">
                {{ message }}
            </div>
            {% endfor %}
        </div>
        {% endif %}
    </div>
    
    <main class="container my-4">
        {% block content %}
        <!-- Contenido principal aquí -->
        {% endblock %}
    </main>

    <footer class="footer">
        <div class="container">
            <div class="row">
                <div class="col-md-4 text-center text-md-start mb-3">
                    <a href="mailto:info@centroavanti.cl" class="d-block">✉️ info@centroavanti.cl</a>
                </div>
                <div class="col-md-4 text-center mb-3">
                    <p class="mb-0">⏰ Horarios:</p>
                    <p class="mb-0">Lunes a Viernes: 08:30 - 20:00 hrs</p>
                    <p class="mb-0">Sábado: 09:00 - 13:00 hrs</p>
                </div>
                <div class="col-md-4 text-center text-md-end">
                    <a href="https://wa.me/56911111111" class="d-block">💬 Whatsapp: +569 1111 1111</a>
                </div>
            </div>
        </div>
    </footer>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js"></script>
    {% block extra_js %}
    {% endblock %}
</body>
</html>

avanti/templates/home.html
{% extends 'base.html' %}
{% load static %}
{% block title %}Inicio{% endblock %}
{% block extra_css %}
<link rel="stylesheet" href="{% static 'css/main.css' %}">
{% endblock %}
{% block content %}

<div class="row">
    <div class="col-md-4">
        <div class="card"> 
            <img src="{% static 'imagenes/Doctores.jpeg' %}" class="card-img-top" alt="Médico">
            <div class="card-body">
                <h5 class="card-title">Acceso Médico</h5>
                <p class="card-text">Accede a tu panel de control como médico.</p>
                <div class="card-footer d-flex justify-content-end">
                    <a href={% url 'administrativo:login' %} class="btn btn-primary w-100">Acceder</a>
                </div>
            </div>
        </div>
    </div>
    <div class="col-md-4">
        <div class="card">
            <img src="{% static 'imagenes/Pacientes.jpg' %}" class="card-img-top" alt="Paciente">
            <div class="card-body">
                <h5 class="card-title">Acceso Paciente</h5>
                <p class="card-text">Consulta tus citas y historial médico.</p>
                <div class="card-footer d-flex justify-content-end">
                    <a href={% url 'administrativo:formulario_reserva' %} class="btn btn-primary w-100">Acceder</a>
                </div>
            </div>
        </div>
    </div>
    <div class="col-md-4">
        <div class="card">
            <img src="{% static 'imagenes/Administrativo.webp' %}" class="card-img-top" alt="Administrativo">
            <div class="card-body">
                <h5 class="card-title">Acceso Administrativo</h5>
                <p class="card.text">Gestiona los registros y citas.</p>
                <div class="card-footer d-flex justify-content-end">
                    <a href={% url 'administrativo:login' %} class="btn btn-primary w-100">Acceder</a>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}